### ISSUE TITLE
An item with the same key already exists

### ISSUE THREAD

**Issue by ffMathy** [andrewlock/dotnet-config2json#1]
I get the following error.

> System.ArgumentException: An item with the same key has already been added. Key: appSettings
>    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
>    at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
>    at Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider..ctor(MemoryConfigurationSource source)
>    at Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.Build(IConfigurationBuilder builder)
>    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
>    at Config2Json.FileMigrator.MigrateFile(String file) in C:\projects\dotnet-config2json\src\dotnet-config2json\FileMigrator.cs:line 65

**Comment by andrewlock** [comment]
Thanks for the report - would you be able to share a copy of the config file you're trying to convert (feel free to obfuscate any sensitive values - the keys are the important bit)?

**Comment by kkesselwss** [comment]
Having similar issues:

```Checking 'Web.config'...
Path 'Web.config' is a file
Migrating Web.config...
An error occurred migrating Web.config:
System.ArgumentException: An item with the same key has already been added. Key: appSettings
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.Extensions.Configuration.Memory.MemoryConfigurationProvider..ctor(MemoryConfigurationSource source)
   at Microsoft.Extensions.Configuration.Memory.MemoryConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Config2Json.FileMigrator.MigrateFile(String file) in C:\projects\dotnet-config2json\src\dotnet-config2json\FileMigrator.cs:line 65
Migration complete.```

My `Web.config` is setup like so:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <add key="Setting" value="SettingValue" />
    <add key="Setting2" value="SettingValue2" />
    <add key="Setting3" value="SettingValue3" />
  </appSettings>
</configuration>
```

**Comment by andrewlock** [comment]
Thanks both, I've just tested this out and I'm pushing out a fix now. It should be available on NuGet soon
